### ISSUE TITLE
go search console panic error

### ISSUE THREAD

**Issue by Seryaltuncer** [googleapis/google-api-go-client#1402]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - Programming language: Go 1.17.5
  - OS: MacOS BigSur 11.6.2
  - Language runtime version: -
  - Package version: v0.63

#### Steps to reproduce
  Maybe error gets from client and request side Needs checks.
  1. Example Code Block
  ```go
response, err := searchconsoleService.Sites.List().Do()
	if err != nil {
		fmt.Printf(err.Error())
	}

	fmt.Printf("sites[%#v] \n", response)

	for _, site := range response.SiteEntry {
		fmt.Printf("site[%#v] \n", site)
	}
   ``` 
  2. When I run the code I am getting this error
  ```sh
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12e689b]
  ```
Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by codyoss** [comment]
Hey @Seryaltuncer what line is causing the panic? When you are checking the error on the request I would log.Fatal there. If you have an error and keep processing data the for loop line will indeed panic.

**Comment by muratmirgun** [comment]
@codyoss The error occurs during the request throw in the client in the same way that I am experiencing the problem, if you want, I can throw the error through debug.

**Comment by codyoss** [comment]
Can you please provide:
- a full minimal example showing how you initialize the client too
- is there a line number of the code called in the panic trace?
- Any extra info you have would be great so I can try to reproduce

**Comment by muratmirgun** [comment]
My specs:
Go Version: 1.17.5
OS: MacOS M1 12.1 Monterey

### I debug the code on Goland and panics goes from  this function. 
https://github.com/googleapis/google-api-go-client/blob/d972e9ab6fb1ad74573305f1f0e31c7a9f588727/internal/gensupport/send.go#L21

### The Error is :
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104c20f60]

goroutine 1 [running]:
golang.org/x/oauth2/authhandler.authHandlerSource.Token({{0x10500b8b0, 0x1400002c090}, 0x140001e7260, 0x0, {0x0, 0x0}})
        /Users/muratmirgun/GolandProjects/project/vendor/golang.org/x/oauth2/authhandler/authhandler.go:48 +0x70
golang.org/x/oauth2.(*reuseTokenSource).Token(0x14000020be0)
        /Users/muratmirgun/GolandProjects/project/vendor/golang.org/x/oauth2/oauth2.go:304 +0x118
golang.org/x/oauth2.(*Transport).RoundTrip(0x14000020c20, 0x1400012cb00)
        /Users/muratmirgun/GolandProjects/project/vendor/golang.org/x/oauth2/transport.go:45 +0xdc
net/http.send(0x1400012cb00, {0x104ffe020, 0x14000020c20}, {0x0, 0x0, 0x0})
        /opt/homebrew/Cellar/go/1.17.5/libexec/src/net/http/client.go:252 +0x410
net/http.(*Client).send(0x140001a5680, 0x1400012cb00, {0x0, 0x0, 0x0})
        /opt/homebrew/Cellar/go/1.17.5/libexec/src/net/http/client.go:176 +0x110
net/http.(*Client).do(0x140001a5680, 0x1400012cb00)
        /opt/homebrew/Cellar/go/1.17.5/libexec/src/net/http/client.go:725 +0xf48
net/http.(*Client).Do(0x140001a5680, 0x1400012cb00)
        /opt/homebrew/Cellar/go/1.17.5/libexec/src/net/http/client.go:593 +0x40
google.golang.org/api/internal/gensupport.SendRequest({0x0, 0x0}, 0x140001a5680, 0x1400012cb00)
        /Users/muratmirgun/GolandProjects/project/vendor/google.golang.org/api/internal/gensupport/send.go:28 +0x168
google.golang.org/api/searchconsole/v1.(*SitesListCall).doRequest(0x14000033980, {0x104e72a6a, 0x4})
        /Users/muratmirgun/GolandProjects/project/vendor/google.golang.org/api/searchconsole/v1/searchconsole-gen.go:2136 +0x4e0
google.golang.org/api/searchconsole/v1.(*SitesListCall).Do(0x14000033980, {0x0, 0x0, 0x0})
        /Users/muratmirgun/GolandProjects/project/vendor/google.golang.org/api/searchconsole/v1/searchconsole-gen.go:2148 +0x84
seoman/cmd.glob..func1(0x1053a5020, {0x1053e02f8, 0x0, 0x0})
        /Users/muratmirgun/GolandProjects/project/cmd/auth.go:29 +0x230
github.com/spf13/cobra.(*Command).execute(0x1053a5020, {0x1053e02f8, 0x0, 0x0})
        /Users/muratmirgun/GolandProjects/project/vendor/github.com/spf13/cobra/command.go:860 +0xa04
github.com/spf13/cobra.(*Command).ExecuteC(0x1053a52a0)
        /Users/muratmirgun/GolandProjects/project/vendor/github.com/spf13/cobra/command.go:974 +0x7b8
github.com/spf13/cobra.(*Command).Execute(0x1053a52a0)
        /Users/muratmirgun/GolandProjects/project/vendor/github.com/spf13/cobra/command.go:902 +0x30
seoman/cmd.Execute()
        /Users/muratmirgun/GolandProjects/project/cmd/root.go:27 +0x30
main.main()
        /Users/muratmirgun/GolandProjects/project/main.go:6 +0x20
Exiting.

Debugger finished with the exit code 0

```
 
## Check this code for minimal for client get sites example:
```go
ctx := context.Background()

option.WithCredentials(&google.Credentials{})
svc, err := searchconsole.NewService(ctx, option.WithCredentialsFile("./client_secrets.json"))
if err != nil {
	fmt.Println(err.Error())
}

response, err := svc.Sites.List().Do()
if err != nil {
	fmt.Printf(err.Error())
}
fmt.Println(response)
```

**Comment by codyoss** [comment]
I copy pasted that exact code /w v0.63.0 and it worked for me. The only difference I can think of is something is not quite right with your pathing to the service account file. The static trace stems from the auth layer, so maybe something is not initialized quite right there?

**Comment by codyoss** [comment]
I am going to close this issue out as I am fairly confident this is not an issue in the generated client here. Like I said in the comment above I think the issue might be resolving your SA file.
