### ISSUE TITLE
admob client source.authHandler is nil

### ISSUE THREAD

**Issue by liqingping** [googleapis/google-api-go-client#1976]
env:
GOVERSION="go1.17.11"
mac os big sur

code :
```package main

import (
	"context"
	"fmt"
	"google.golang.org/api/admob/v1"
	"google.golang.org/api/option"
)

func main() {
	ctx := context.Background()
	admobService, err := admob.NewService(ctx, option.WithCredentialsFile("../../Desktop/client_secret_116869809920-rsvdb41lqd206s9aq1l4k8g48l4qrkf1.apps.googleusercontent.com.json"))
	if err != nil {
		fmt.Println(err)
		return
	}
	res, err := admobService.Accounts.Get("accounts/pub-xxxxxxx").Do()
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(err)
	fmt.Println(res)
}
```

code run result:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14c8d7d]

goroutine 1 [running]:
golang.org/x/oauth2/authhandler.authHandlerSource.Token({{0x1715cd0, 0xc00012c000}, 0xc0004aa150, 0x0, {0x0, 0x0}, 0x0})
        /Users/liqp/go/pkg/mod/golang.org/x/oauth2@v0.7.0/authhandler/authhandler.go:80 +0x1bd
golang.org/x/oauth2.(*reuseTokenSource).Token(0xc000300ea0)
        /Users/liqp/go/pkg/mod/golang.org/x/oauth2@v0.7.0/oauth2.go:307 +0xd5
golang.org/x/oauth2.(*Transport).RoundTrip(0xc000150ba0, 0xc0001cc300)
        /Users/liqp/go/pkg/mod/golang.org/x/oauth2@v0.7.0/transport.go:45 +0xa7
net/http.send(0xc0001cc300, {0x1705040, 0xc000150ba0}, {0x1630900, 0x12c4001, 0x0})
        /usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc000300f30, 0xc0001cc300, {0x14, 0x100e6b4, 0x0})
        /usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc000300f30, 0xc0001cc300)
        /usr/local/go/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
google.golang.org/api/internal/gensupport.SendRequest({0x0, 0x0}, 0x1643e75, 0xc0001cc300)
        /Users/liqp/go/pkg/mod/google.golang.org/api@v0.122.0/internal/gensupport/send.go:52 +0x86
google.golang.org/api/admob/v1.(*AccountsGetCall).doRequest(0xc00047ff28, {0x1643df5, 0x4})
        /Users/liqp/go/pkg/mod/google.golang.org/api@v0.122.0/admob/v1/admob-gen.go:1858 +0x737
google.golang.org/api/admob/v1.(*AccountsGetCall).Do(0xc00047ff28, {0x0, 0xc00047ff18, 0x1})
        /Users/liqp/go/pkg/mod/google.golang.org/api@v0.122.0/admob/v1/admob-gen.go:1870 +0x6d
main.main()
        /Users/liqp/droi/test/test.go:22 +0x16e
```

**Comment by liqingping** [comment]
Thanks for the proposal. I'll try it

**Comment by codyoss** [comment]
Closing due to lack of response.
