### ISSUE TITLE
bundler: TestConcurrentHandlersMax does not terminate

### ISSUE THREAD

**Issue by escholtz** [googleapis/google-api-go-client#417]
Occasionally, TestConcurrentHandlersMax does not terminate.

Steps to reproduce:

```bash
# will eventually hang
go test -run TestConcurrentHandlersMax -v -count 10000

# will eventually terminate with too many goroutines
go test -race -run TestConcurrentHandlersMax -v -count 10000
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
exit status 66
```

It appears others are seeing this issue:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927114

go version go1.13 linux/amd64
google-api-go-client at d63bd5fbc004a083dc85ef622366115e8088da62

**Comment by escholtz** [comment]
Evidence of runaway goroutine count (250,832) on 6-core 3.7ghz linux desktop.

```
diff --git a/support/bundler/bundler_test.go b/support/bundler/bundler_test.go
index c716adc86..e7b289de0 100644
--- a/support/bundler/bundler_test.go
+++ b/support/bundler/bundler_test.go
@@ -7,7 +7,9 @@ package bundler
 import (
 	"context"
 	"fmt"
+	"os"
 	"reflect"
+	"runtime/pprof"
 	"sync"
 	"testing"
 	"time"
@@ -239,6 +241,12 @@ func TestConcurrentHandlersMax(t *testing.T) {
 	b.HandlerLimit = 10
 	defer b.Flush()
 
+	go func() {
+		time.Sleep(2000 * time.Millisecond)
+		pprof.Lookup("goroutine").WriteTo(os.Stdout, 1)
+		panic("timeout")
+	}()
+
 	more := 0 // extra iterations past saturation
 	for i := 0; more == 0 || i < more; i++ {
 		mu.Lock()


$ go test -run TestConcurrentHandlersMax -v -count 10000
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.06s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.02s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.02s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.04s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.02s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.00s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.02s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.02s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.02s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.00s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.00s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.55s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.02s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.00s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.01s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.00s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.00s)
=== RUN   TestConcurrentHandlersMax
--- PASS: TestConcurrentHandlersMax (0.00s)
=== RUN   TestConcurrentHandlersMax

goroutine profile: total 250832
126954 @ 0x4300e0 0x4416c8 0x44169e 0x4680ad 0x50106e 0x504ddb 0x45d1b1
#	0x44169d	sync.runtime_notifyListWait+0xcd						src/runtime/sema.go:510
#	0x4680ac	sync.(*Cond).Wait+0x9c								src/sync/cond.go:56
#	0x50106d	google.golang.org/api/support/bundler.(*Bundler).acquire+0x9d			go/src/google-api-go-client/support/bundler/bundler.go:276
#	0x504dda	google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1+0xca	go/src/google-api-go-client/support/bundler/bundler.go:261

114713 @ 0x4300e0 0x4406c0 0x4406ab 0x440427 0x46985c 0x469747 0x4680c3 0x50106e 0x504ddb 0x45d1b1
#	0x440426	sync.runtime_SemacquireMutex+0x46						src/runtime/sema.go:71
#	0x46985b	sync.(*Mutex).lockSlow+0xfb							src/sync/mutex.go:138
#	0x469746	sync.(*Mutex).Lock+0x46								src/sync/mutex.go:81
#	0x4680c2	sync.(*Cond).Wait+0xb2								src/sync/cond.go:57
#	0x50106d	google.golang.org/api/support/bundler.(*Bundler).acquire+0x9d			go/src/google-api-go-client/support/bundler/bundler.go:276
#	0x504dda	google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1+0xca	go/src/google-api-go-client/support/bundler/bundler.go:261

9124 @ 0x4300e0 0x4406c0 0x4406ab 0x440427 0x46985c 0x50110e 0x500ff2 0x504ddb 0x45d1b1
#	0x440426	sync.runtime_SemacquireMutex+0x46						src/runtime/sema.go:71
#	0x46985b	sync.(*Mutex).lockSlow+0xfb							src/sync/mutex.go:138
#	0x50110d	sync.(*Mutex).Lock+0x13d							src/sync/mutex.go:81
#	0x500ff1	google.golang.org/api/support/bundler.(*Bundler).acquire+0x21			go/src/google-api-go-client/support/bundler/bundler.go:270
#	0x504dda	google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1+0xca	go/src/google-api-go-client/support/bundler/bundler.go:261

24 @ 0x4300e0 0x44baa7 0x44ba7d 0x5055ee 0x45d1b1
#	0x44ba7c	time.Sleep+0x12c								src/runtime/time.go:105
#	0x5055ed	google.golang.org/api/support/bundler.TestConcurrentHandlersMax.func2+0x2d	go/src/google-api-go-client/support/bundler/bundler_test.go:245

6 @ 0x4300e0 0x4406c0 0x4406ab 0x4322ee 0x4322d2 0x429256 0x4f71be 0x4f7030 0x4f3c4a 0x505636 0x45d1b1
#	0x4f71bd	runtime/pprof.writeRuntimeProfile+0x3d						src/runtime/pprof/pprof.go:702
#	0x4f702f	runtime/pprof.writeGoroutine+0x9f						src/runtime/pprof/pprof.go:670
#	0x4f3c49	runtime/pprof.(*Profile).WriteTo+0x3d9						src/runtime/pprof/pprof.go:329
#	0x505635	google.golang.org/api/support/bundler.TestConcurrentHandlersMax.func2+0x75	go/src/google-api-go-client/support/bundler/bundler_test.go:246

3 @ 0x41a802 0x40c086 0x44427c 0x4f71eb 0x4f7030 0x4f3c4a 0x505636 0x45d1b1
#	0x4f71ea	runtime/pprof.writeRuntimeProfile+0x6a						src/runtime/pprof/pprof.go:707
#	0x4f702f	runtime/pprof.writeGoroutine+0x9f						src/runtime/pprof/pprof.go:670
#	0x4f3c49	runtime/pprof.(*Profile).WriteTo+0x3d9						src/runtime/pprof/pprof.go:329
#	0x505635	google.golang.org/api/support/bundler.TestConcurrentHandlersMax.func2+0x75	go/src/google-api-go-client/support/bundler/bundler_test.go:246

2 @ 0x440436 0x46985c 0x469747 0x4680c3 0x50106e 0x504ddb 0x45d1b1
#	0x440435	sync.runtime_SemacquireMutex+0x55						src/runtime/sema.go:70
#	0x46985b	sync.(*Mutex).lockSlow+0xfb							src/sync/mutex.go:138
#	0x469746	sync.(*Mutex).Lock+0x46								src/sync/mutex.go:81
#	0x4680c2	sync.(*Cond).Wait+0xb2								src/sync/cond.go:57
#	0x50106d	google.golang.org/api/support/bundler.(*Bundler).acquire+0x9d			go/src/google-api-go-client/support/bundler/bundler.go:276
#	0x504dda	google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1+0xca	go/src/google-api-go-client/support/bundler/bundler.go:261

1 @ 0x40a867 0x440628 0x4322ee 0x4322d2 0x429256 0x4f7215 0x4f7030 0x4f3c4a 0x505636 0x45d1b1
#	0x4f7214	runtime/pprof.writeRuntimeProfile+0x94						src/runtime/pprof/pprof.go:708
#	0x4f702f	runtime/pprof.writeGoroutine+0x9f						src/runtime/pprof/pprof.go:670
#	0x4f3c49	runtime/pprof.(*Profile).WriteTo+0x3d9						src/runtime/pprof/pprof.go:329
#	0x505635	google.golang.org/api/support/bundler.TestConcurrentHandlersMax.func2+0x75	go/src/google-api-go-client/support/bundler/bundler_test.go:246

1 @ 0x40a867 0x440628 0x440427 0x46985c 0x50110e 0x500ff2 0x504ddb 0x45d1b1
#	0x440426	sync.runtime_SemacquireMutex+0x46						src/runtime/sema.go:71
#	0x46985b	sync.(*Mutex).lockSlow+0xfb							src/sync/mutex.go:138
#	0x50110d	sync.(*Mutex).Lock+0x13d							src/sync/mutex.go:81
#	0x500ff1	google.golang.org/api/support/bundler.(*Bundler).acquire+0x21			go/src/google-api-go-client/support/bundler/bundler.go:270
#	0x504dda	google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1+0xca	go/src/google-api-go-client/support/bundler/bundler.go:261

1 @ 0x4300e0 0x4059c8 0x40599e 0x4056cb 0x4c5b37 0x4c9408 0x4c5769 0x4c7057 0x4c5fa6 0x505ce5 0x42fcfe 0x45d1b1
#	0x4c5b36	testing.(*T).Run+0x376		src/testing/testing.go:961
#	0x4c9407	testing.runTests.func1+0x77	src/testing/testing.go:1204
#	0x4c5768	testing.tRunner+0xc8		src/testing/testing.go:909
#	0x4c7056	testing.runTests+0x2a6		src/testing/testing.go:1202
#	0x4c5fa5	testing.(*M).Run+0x175		src/testing/testing.go:1119
#	0x505ce4	main.main+0x134			_testmain.go:62
#	0x42fcfd	runtime.main+0x21d		src/runtime/proc.go:203

1 @ 0x4404f5 0x44182f 0x46815c 0x5010dc 0x504ddb 0x45d1b1
#	0x44182e	sync.runtime_notifyListNotifyAll+0x8e						src/runtime/sema.go:544
#	0x46815b	sync.(*Cond).Broadcast+0x5b							src/sync/cond.go:75
#	0x5010db	google.golang.org/api/support/bundler.(*Bundler).acquire+0x10b			go/src/google-api-go-client/support/bundler/bundler.go:285
#	0x504dda	google.golang.org/api/support/bundler.(*Bundler).startFlushLocked.func1+0xca	go/src/google-api-go-client/support/bundler/bundler.go:261

1 @ 0x4f7215 0x4f7030 0x4f3c4a 0x505636 0x45d1b1
#	0x4f7214	runtime/pprof.writeRuntimeProfile+0x94						src/runtime/pprof/pprof.go:708
#	0x4f702f	runtime/pprof.writeGoroutine+0x9f						src/runtime/pprof/pprof.go:670
#	0x4f3c49	runtime/pprof.(*Profile).WriteTo+0x3d9						src/runtime/pprof/pprof.go:329
#	0x505635	google.golang.org/api/support/bundler.TestConcurrentHandlersMax.func2+0x75	go/src/google-api-go-client/support/bundler/bundler_test.go:246

1 @ 0x500870 0x503b0b 0x4c5769 0x45d1b1
#	0x50086f	google.golang.org/api/support/bundler.(*Bundler).Add+0xef		go/src/google-api-go-client/support/bundler/bundler.go:146
#	0x503b0a	google.golang.org/api/support/bundler.TestConcurrentHandlersMax+0x1ba	go/src/google-api-go-client/support/bundler/bundler_test.go:259
#	0x4c5768	testing.tRunner+0xc8							src/testing/testing.go:909

panic: timeout

goroutine 1000 [running]:
google.golang.org/api/support/bundler.TestConcurrentHandlersMax.func2()
	go/src/google-api-go-client/support/bundler/bundler_test.go:247 +0x92
created by google.golang.org/api/support/bundler.TestConcurrentHandlersMax
	go/src/google-api-go-client/support/bundler/bundler_test.go:244 +0x167
exit status 2
FAIL	google.golang.org/api/support/bundler	21.131s
```
