### ISSUE TITLE
support/bundler.Bundler can deadlock when using time based flush

### ISSUE THREAD

**Issue by entombedvirus** [googleapis/google-api-go-client#475]
bundler.Bundler can run into a deadlock under the following
configuration:

- handler limit of 1
- high size and count thresholds such that the only reason a bundle is
flushed is because of the delay timer expiring

Under these conditions, with high concurrency, a deadlock can happen
because the background handler goroutine can exit while there is a
pending queue, which will never get flushed.

This can be repro-ed on latest master, regardless of go version as of filing (4554f64b6b0b7213cbe6bf75678cacc28ed28a03).

I'll post a PR with a fix + test some time later today.

**Comment by entombedvirus** [comment]
Review with test plus fix: https://code-review.googlesource.com/c/google-api-go-client/+/55950

**Comment by entombedvirus** [comment]
Please let me know if I can provide any more info to help close this issue.

**Comment by codyoss** [comment]
Thank you for the report and contribution, I will take a look!

**Comment by siretart** [comment]
It seems that the test introduced by https://github.com/googleapis/google-api-go-client/commit/6114940689b1dffd822bbe77408bce0b0b9d84f7 is hanging/deadlocking for me:

```
    bundler_test.go:402: timed out: context canceled
panic: test timed out after 10m0s
running tests:
	TestBundlerTimeBasedFlushDeadlock (9m57s)

goroutine 1205 [running]:
testing.(*M).startAlarm.func1()
	/usr/lib/go-1.22/src/testing/testing.go:2366 +0x385
created by time.goFunc
	/usr/lib/go-1.22/src/time/sleep.go:177 +0x2d

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0000d6340, {0x556943?, 0x0?}, 0x55bf28)
	/usr/lib/go-1.22/src/testing/testing.go:1750 +0x3ab
testing.runTests.func1(0xc0000d6340)
	/usr/lib/go-1.22/src/testing/testing.go:2161 +0x37
testing.tRunner(0xc0000d6340, 0xc0000a6c70)
	/usr/lib/go-1.22/src/testing/testing.go:1689 +0xfb
testing.runTests(0xc0000aa0a8, {0x65bdc0, 0xd, 0xd}, {0x1?, 0x4b8aae?, 0x6605a0?})
	/usr/lib/go-1.22/src/testing/testing.go:2159 +0x445
testing.(*M).Run(0xc0000b00a0)
	/usr/lib/go-1.22/src/testing/testing.go:2027 +0x68b
main.main()
	_testmain.go:79 +0x16c

goroutine 7 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc0004aff08?)
	/usr/lib/go-1.22/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0x5856c8?)
	/usr/lib/go-1.22/src/sync/waitgroup.go:116 +0x48
google.golang.org/api/support/bundler.TestBundlerTimeBasedFlushDeadlock(0xc000304000)
	/tmp/autopkgtest.pxElVg/build.3uJ/src/obj-x86_64-linux-gnu/src/google.golang.org/api/support/bundler/bundler_test.go:413 +0x1b2
testing.tRunner(0xc000304000, 0x55bf28)
	/usr/lib/go-1.22/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/usr/lib/go-1.22/src/testing/testing.go:1742 +0x390

goroutine 54 [select (no cases), 9 minutes]:
google.golang.org/api/support/bundler.TestBundlerErrors.func1({0x522040?, 0xc0001840d8?})
	/tmp/autopkgtest.pxElVg/build.3uJ/src/obj-x86_64-linux-gnu/src/google.golang.org/api/support/bundler/bundler_test.go:245 +0xf
google.golang.org/api/support/bundler.(*Bundler).handle(0xc0001a20b0, 0xc00018c0b0?)
	/tmp/autopkgtest.pxElVg/build.3uJ/src/obj-x86_64-linux-gnu/src/google.golang.org/api/support/bundler/bundler.go:324 +0x44
created by google.golang.org/api/support/bundler.(*Bundler).enqueueCurBundle in goroutine 53
	/tmp/autopkgtest.pxElVg/build.3uJ/src/obj-x86_64-linux-gnu/src/google.golang.org/api/support/bundler/bundler.go:179 +0x148

goroutine 78 [chan receive, 9 minutes]:
google.golang.org/api/support/bundler.TestAddWait.func2({0x522040?, 0xc000184018?})
	/tmp/autopkgtest.pxElVg/build.3uJ/src/obj-x86_64-linux-gnu/src/google.golang.org/api/support/bundler/bundler_test.go:198 +0x25
google.golang.org/api/support/bundler.(*Bundler).handle(0xc0001320b0, 0x1af?)
	/tmp/autopkgtest.pxElVg/build.3uJ/src/obj-x86_64-linux-gnu/src/google.golang.org/api/support/bundler/bundler.go:324 +0x44
created by google.golang.org/api/support/bundler.(*Bundler).enqueueCurBundle in goroutine 77
	/tmp/autopkgtest.pxElVg/build.3uJ/src/obj-x86_64-linux-gnu/src/google.golang.org/api/support/bundler/bundler.go:179 +0x148
FAIL	google.golang.org/api/support/bundler	600.035s
testing: warning: no tests to run
