### ISSUE TITLE
transport/grpc: TestDialWithDirectPathEnabled failures

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-api-go-client#790]
From the builds:
```
--- FAIL: TestDialWithDirectPathEnabled (0.02s)
    dial_socketopt_test.go:107: DialGRPC: error context deadline exceeded, want nil
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb890c6]

goroutine 9 [running]:
testing.tRunner.func1(0xc0002a8200)
	/usr/local/go/src/testing/testing.go:874 +0x69f
panic(0xce5080, 0x1364340)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
google.golang.org/grpc.(*ClientConn).Close(0x0, 0x0, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.34.0/clientconn.go:1029 +0x56
panic(0xce5080, 0x1364340)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
google.golang.org/grpc.(*ClientConn).Invoke(0x0, 0xeb6a20, 0xc000072d20, 0xdab6a0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/google.golang.org/grpc@v1.34.0/call.go:32 +0x48
google.golang.org/grpc.Invoke(...)
	/root/go/pkg/mod/google.golang.org/grpc@v1.34.0/call.go:60
google.golang.org/api/transport/grpc.TestDialWithDirectPathEnabled(0xc0002a8200)
	/root/go/src/google.golang.org/api/transport/grpc/dial_socketopt_test.go:112 +0x43a
testing.tRunner(0xc0002a8200, 0xdd6638)
	/usr/local/go/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x652
FAIL	google.golang.org/api/transport/grpc	0.074s
```

**Comment by codyoss** [comment]
@mohanli-ml Can you take a look at this?

**Comment by mohanli-ml** [comment]
@codyoss I can not reproduce the error from HEAD, i.e., on a DirectPath enabled cloud VM, the following command can pass. 
`git clone https://github.com/googleapis/google-api-go-client.git`
`cd google-api-go-client/transport/grpc/`
`go test -v -run="TestDialWithDirectPathEnabled"`
Can you tell me how to reproduce the error?

**Comment by codyoss** [comment]
@mohanli-ml I am not sure how to reproduce this. But it seems to happen occasionally(It just happened again today on our continuous build).

**Comment by codyoss** [comment]
I am going to skip the test for now to keep the branch green, but this should still be investigated.

**Comment by codyoss** [comment]
Closing this for now as I don't believe this is an issue any longer.
